repos:
  # Code Formatting
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        files: 'ledzephyr_lean\.py|test_lean\.py'

  # Code Quality & Security
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        files: 'ledzephyr_lean\.py|test_lean\.py'
      - id: ruff-format
        files: 'ledzephyr_lean\.py|test_lean\.py'

  # Type Checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        files: 'ledzephyr_lean\.py|test_lean\.py'
        additional_dependencies: [types-requests]

  # Security Scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        files: 'ledzephyr_lean\.py'