version: '3.8'

services:
  ledzephyr:
    build:
      context: .
      dockerfile: Dockerfile
    image: ledzephyr:local
    container_name: ledzephyr
    environment:
      - LEDZEPHYR_JIRA_URL=${LEDZEPHYR_JIRA_URL}
      - LEDZEPHYR_JIRA_USERNAME=${LEDZEPHYR_JIRA_USERNAME}
      - LEDZEPHYR_JIRA_API_TOKEN=${LEDZEPHYR_JIRA_API_TOKEN}
      - LEDZEPHYR_ZEPHYR_TOKEN=${LEDZEPHYR_ZEPHYR_TOKEN}
      - LEDZEPHYR_QTEST_URL=${LEDZEPHYR_QTEST_URL}
      - LEDZEPHYR_QTEST_TOKEN=${LEDZEPHYR_QTEST_TOKEN}
      - LEDZEPHYR_CACHE_DIR=/app/cache
      - LEDZEPHYR_LOG_LEVEL=${LEDZEPHYR_LOG_LEVEL:-INFO}
    volumes:
      - ./cache:/app/cache
      - ./gold:/app/gold:ro
      - ./specs:/app/specs:ro
      - ./reports:/app/reports
    working_dir: /app
    command: metrics -p ${PROJECT_KEY:-DEMO} -w 7d --format table

  # Development container with hot reload
  ledzephyr-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ledzephyr:dev
    container_name: ledzephyr-dev
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - poetry-cache:/root/.cache/pypoetry
    working_dir: /app
    command: poetry run python -m ledzephyr.cli --help
    profiles:
      - dev

  # Test runner container
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    image: ledzephyr:test
    container_name: ledzephyr-test
    environment:
      - HYPOTHESIS_PROFILE=ci
      - PYTEST_ADDOPTS=-v --tb=short
    volumes:
      - ./tests:/app/tests:ro
      - ./gold:/app/gold:ro
      - test-reports:/app/test_reports
    working_dir: /app
    command: poetry run pytest tests/
    profiles:
      - test

  # School-of-fish test runner
  school-runner:
    build:
      context: .
      dockerfile: Dockerfile
    image: ledzephyr:schools
    container_name: ledzephyr-schools
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./tests:/app/tests:ro
      - ./gold:/app/gold:ro
      - school-metrics:/app/test_reports/school_metrics
    working_dir: /app
    command: poetry run python -m tests.integration.schools.cli --workers 4
    profiles:
      - schools

volumes:
  poetry-cache:
  test-reports:
  school-metrics:

networks:
  default:
    name: ledzephyr-network