[tool.poetry]
name = "ledzephyr"
version = "1.0.0"
description = "Lean utility for Zephyr Scale to qTest migration metrics"
authors = ["LedZephyr Team"]
readme = "README.md"
python = "^3.11"
packages = [{include = "ledzephyr_lean.py"}]

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.7"
httpx = "^0.27.0"
rich = "^13.7.0"

[tool.poetry.scripts]
ledzephyr = "ledzephyr_lean:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"